repos:
  - repo: local
    hooks:
    - id: clang-format
      name: Verify correct formating of C++ files
      language: system
      entry: clang-format --dry-run -Werror
      files: \.(c|h|cc|hh|hxx)$
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
